@echo off
setlocal

if "%UNITY_EXE%"=="" (
    set "UNITY_EXE=C:\Program Files\Unity 6000.2.7f2\Editor\Unity.exe"
)

set "PROJECT_DIR=%~dp0..\.."
for %%I in ("%PROJECT_DIR%") do set "PROJECT_DIR=%%~fI"

if not exist "%UNITY_EXE%" (
    echo Unity executable not found: %UNITY_EXE%
    exit /b 1
)

set "AIIMAGE_BATCH_METHOD="
if "%AIIMAGE_MONAI_BASELINE_MANIFEST%"=="" set "AIIMAGE_MONAI_BASELINE_MANIFEST=%PROJECT_DIR%\Tools\MonaiToNCNN\manual_test\brats_mri_segmentation_baseline\RegLib_C01_1\baseline_manifest.json"
if "%AIIMAGE_MONAI_USE_BASELINE_TENSOR%"=="" set "AIIMAGE_MONAI_USE_BASELINE_TENSOR=1"
if "%AIIMAGE_MONAI_INPUT_PATHS%"=="" if /I not "%AIIMAGE_MONAI_USE_BASELINE_TENSOR%"=="1" set "AIIMAGE_MONAI_INPUT_PATHS=E:\Projects\CTData\sliceexampledata2\MRBrainTumor1\RegLib_C01_1.nrrd"
if "%AIIMAGE_MONAI_COMPARE_BASELINE%"=="" set "AIIMAGE_MONAI_COMPARE_BASELINE=1"
if "%AIIMAGE_MONAI_ENABLE_DUMP%"=="" set "AIIMAGE_MONAI_ENABLE_DUMP=1"
if "%AIIMAGE_MONAI_DUMP_LARGE_TENSORS%"=="" set "AIIMAGE_MONAI_DUMP_LARGE_TENSORS=1"
if "%AIIMAGE_MONAI_FORCE_BUFFER_ALL%"=="" set "AIIMAGE_MONAI_FORCE_BUFFER_ALL=0"
if "%AIIMAGE_MONAI_FORCE_CPU_GEMM%"=="" set "AIIMAGE_MONAI_FORCE_CPU_GEMM=0"
if "%AIIMAGE_MONAI_FORCE_BUFFER_OUTPUTS_DIMS4%"=="" set "AIIMAGE_MONAI_FORCE_BUFFER_OUTPUTS_DIMS4=0"
if "%AIIMAGE_MONAI_DEBUG_PINNED_BLOBS%"=="" set "AIIMAGE_MONAI_DEBUG_PINNED_BLOBS="
if "%AIIMAGE_MONAI_OUTPUT_BLOB%"=="" set "AIIMAGE_MONAI_OUTPUT_BLOB=out0"
if "%AIIMAGE_MONAI_PROBE_ONLY%"=="" set "AIIMAGE_MONAI_PROBE_ONLY=0"
if "%AIIMAGE_MONAI_MAX_PATCHES%"=="" set "AIIMAGE_MONAI_MAX_PATCHES=0"
if "%AIIMAGE_MONAI_CLEAR_TEMP_POOL_EACH_PATCH%"=="" set "AIIMAGE_MONAI_CLEAR_TEMP_POOL_EACH_PATCH=1"
if "%AIIMAGE_MONAI_TEMP_POOL_CLEAR_INTERVAL%"=="" set "AIIMAGE_MONAI_TEMP_POOL_CLEAR_INTERVAL=1"
if "%AIIMAGE_MONAI_YIELD_INTERVAL%"=="" set "AIIMAGE_MONAI_YIELD_INTERVAL=1"
if "%AIIMAGE_MONAI_MANAGED_CLEANUP_INTERVAL%"=="" set "AIIMAGE_MONAI_MANAGED_CLEANUP_INTERVAL=1"
if "%AIIMAGE_MONAI_RESOURCE_SNAPSHOT_INTERVAL%"=="" set "AIIMAGE_MONAI_RESOURCE_SNAPSHOT_INTERVAL=1"
if "%AIIMAGE_MONAI_ABORT_PRIVATE_MEMORY_MB%"=="" set "AIIMAGE_MONAI_ABORT_PRIVATE_MEMORY_MB=8192"
if "%AIIMAGE_REPRO_TEMP_POOL%"=="" set "AIIMAGE_REPRO_TEMP_POOL=0"
if "%AIIMAGE_BATCH_TIMEOUT_MINUTES%"=="" set "AIIMAGE_BATCH_TIMEOUT_MINUTES=10"

"%UNITY_EXE%" ^
  -batchmode ^
  -quit ^
  -projectPath "%PROJECT_DIR%" ^
  -executeMethod NcnnDebugRunner.RunMonaiDebugBatch ^
  %*

set "EXIT_CODE=%ERRORLEVEL%"
endlocal & exit /b %EXIT_CODE%
