@echo off
setlocal

if "%UNITY_EXE%"=="" (
    set "UNITY_EXE=C:\Program Files\Unity 6000.2.7f2\Editor\Unity.exe"
)

set "SCRIPT_DIR=%~dp0"
set "PROJECT_DIR=%~dp0..\.."
for %%I in ("%PROJECT_DIR%") do set "PROJECT_DIR=%%~fI"
set "TIMEOUT_HELPER=%SCRIPT_DIR%Vista3D\Invoke-WithTimeout.ps1"

if not exist "%UNITY_EXE%" (
    echo [RunVista3DUnityDebug] Unity executable not found: %UNITY_EXE%
    exit /b 1
)

if "%AIIMAGE_VISTA_INPUT_PATH%"=="" set "AIIMAGE_VISTA_INPUT_PATH=E:\Projects\CTData\sliceexampledata2\CT_Philips\CT_Philips.nii.gz"
if "%AIIMAGE_VISTA_BASELINE_MANIFEST%"=="" set "AIIMAGE_VISTA_BASELINE_MANIFEST=%SCRIPT_DIR%manual_test\vista3d_ct_philips_heart_baseline\ct_philips_heart\baseline_manifest.json"
if "%AIIMAGE_MONAI_BASELINE_MANIFEST%"=="" set "AIIMAGE_MONAI_BASELINE_MANIFEST=%AIIMAGE_VISTA_BASELINE_MANIFEST%"
if "%AIIMAGE_MONAI_INPUT_PATHS%"=="" set "AIIMAGE_MONAI_INPUT_PATHS=%AIIMAGE_VISTA_INPUT_PATH%"
if "%AIIMAGE_MONAI_USE_BASELINE_TENSOR%"=="" set "AIIMAGE_MONAI_USE_BASELINE_TENSOR=1"
if "%AIIMAGE_MONAI_COMPARE_BASELINE%"=="" set "AIIMAGE_MONAI_COMPARE_BASELINE=1"
if "%AIIMAGE_MONAI_ENABLE_DUMP%"=="" set "AIIMAGE_MONAI_ENABLE_DUMP=1"
if "%AIIMAGE_MONAI_DUMP_LARGE_TENSORS%"=="" set "AIIMAGE_MONAI_DUMP_LARGE_TENSORS=1"
if "%AIIMAGE_MONAI_FORCE_BUFFER_ALL%"=="" set "AIIMAGE_MONAI_FORCE_BUFFER_ALL=0"
if "%AIIMAGE_MONAI_FORCE_CPU_GEMM%"=="" set "AIIMAGE_MONAI_FORCE_CPU_GEMM=0"
if "%AIIMAGE_MONAI_FORCE_BUFFER_OUTPUTS_DIMS4%"=="" set "AIIMAGE_MONAI_FORCE_BUFFER_OUTPUTS_DIMS4=0"
if "%AIIMAGE_MONAI_PROBE_ONLY%"=="" set "AIIMAGE_MONAI_PROBE_ONLY=1"
if "%AIIMAGE_MONAI_MAX_PATCHES%"=="" set "AIIMAGE_MONAI_MAX_PATCHES=1"
if "%AIIMAGE_MONAI_PACK4_ONLY_GUARD%"=="" set "AIIMAGE_MONAI_PACK4_ONLY_GUARD=1"
if "%AIIMAGE_MONAI_CLEAR_TEMP_POOL_EACH_PATCH%"=="" set "AIIMAGE_MONAI_CLEAR_TEMP_POOL_EACH_PATCH=1"
if "%AIIMAGE_MONAI_TEMP_POOL_CLEAR_INTERVAL%"=="" set "AIIMAGE_MONAI_TEMP_POOL_CLEAR_INTERVAL=1"
if "%AIIMAGE_MONAI_YIELD_INTERVAL%"=="" set "AIIMAGE_MONAI_YIELD_INTERVAL=1"
if "%AIIMAGE_MONAI_MANAGED_CLEANUP_INTERVAL%"=="" set "AIIMAGE_MONAI_MANAGED_CLEANUP_INTERVAL=1"
if "%AIIMAGE_MONAI_RESOURCE_SNAPSHOT_INTERVAL%"=="" set "AIIMAGE_MONAI_RESOURCE_SNAPSHOT_INTERVAL=1"
if "%AIIMAGE_MONAI_ABORT_PRIVATE_MEMORY_MB%"=="" set "AIIMAGE_MONAI_ABORT_PRIVATE_MEMORY_MB=8192"
if "%AIIMAGE_REPRO_TEMP_POOL%"=="" set "AIIMAGE_REPRO_TEMP_POOL=0"
if "%AIIMAGE_BATCH_TIMEOUT_MINUTES%"=="" set "AIIMAGE_BATCH_TIMEOUT_MINUTES=10"
set /a AIIMAGE_BATCH_TIMEOUT_SECONDS=%AIIMAGE_BATCH_TIMEOUT_MINUTES%*60

powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "& { & '%TIMEOUT_HELPER%' -FilePath '%UNITY_EXE%' -ArgumentList @('-batchmode','-quit','-projectPath','%PROJECT_DIR%','-executeMethod','NcnnDebugRunner.RunMonaiDebugBatch') -TimeoutSeconds %AIIMAGE_BATCH_TIMEOUT_SECONDS% -WorkingDirectory '%PROJECT_DIR%' }"

exit /b %errorlevel%
