// Shared pack4 texture slots used by multiple kernel groups.
Texture2DArray<float4> _TexIn0Arr;
Texture2DArray<float4> _TexIn1Arr;
Texture2DArray<float4> _TexIn2Arr;
Texture2DArray<float4> _TexIn3Arr;
RWTexture2DArray<float4> _TexOut0Arr;
RWTexture2DArray<float4> _TexOut1Arr;

#define _AddA _TexIn0Arr
#define _AddB _TexIn1Arr
#define _AddOutArr _TexOut0Arr
#define _CopyInArr _TexIn0Arr
#define _CopyOutArr _TexOut0Arr
#define _ConcatPack4CDHWAInArr _TexIn0Arr
#define _ConcatPack4CDHWBInArr _TexIn1Arr
#define _ConcatPack4CDHWOutArr _TexOut0Arr
#define _SdInpaintLatentsArr _TexIn0Arr
#define _SdInpaintMaskArr _TexIn1Arr
#define _SdInpaintMaskedLatentsArr _TexIn2Arr
#define _SdInpaintInputOutArr _TexOut0Arr
#define _InterpInArr _TexIn0Arr
#define _InterpOutArr _TexOut0Arr
#define _InterpNnInArr _TexIn0Arr
#define _InterpNnOutArr _TexOut0Arr
#define _InterpDownInArr _TexIn0Arr
#define _InterpDownOutArr _TexOut0Arr
#define _InterpDownNnInArr _TexIn0Arr
#define _InterpDownNnOutArr _TexOut0Arr
#define _Pack4InArr _TexIn0Arr
#define _FillOutArr _TexOut0Arr
#define _FillScalarOutArr _TexOut0Arr
#define _ScaleInArr _TexIn0Arr
#define _ScaleOutArr _TexOut0Arr
#define _BiasInArr _TexIn0Arr
#define _BiasOutArr _TexOut0Arr
#define _BatchNormInArr _TexIn0Arr
#define _BatchNormOutArr _TexOut0Arr
#define _LreluInArr _TexIn0Arr
#define _LreluOutArr _TexOut0Arr
#define _NoiseInOutArr _TexOut0Arr
#define _ClipInArr _TexIn0Arr
#define _ClipOutArr _TexOut0Arr
#define _SftInArr _TexIn0Arr
#define _SftCondMulArr _TexIn1Arr
#define _SftCondAddArr _TexIn2Arr
#define _SftOutArr _TexOut0Arr
#define _RgbInArr _TexIn0Arr
#define _ProbeInArr _TexIn0Arr
#define _PadInArr _TexIn0Arr
#define _PadOutArr _TexOut0Arr
#define _PoolInArr _TexIn0Arr
#define _PoolOutArr _TexOut0Arr
#define _Pool4DInArr _TexIn0Arr
#define _Pool4DOutArr _TexOut0Arr
#define _SoftmaxInArr _TexIn0Arr
#define _SoftmaxOutArr _TexOut0Arr
#define _UnaryInArr _TexIn0Arr
#define _UnaryOutArr _TexOut0Arr
#define _BinaryA _TexIn0Arr
#define _BinaryB _TexIn1Arr
#define _BinaryOutArr _TexOut0Arr
#define _ReduceScalar2DInArr _TexIn0Arr
#define _ReduceScalar2DOutArr _TexOut0Arr
#define _ShuffleInArr _TexIn0Arr
#define _ShuffleOutArr _TexOut0Arr
#define _CropPack4InArr _TexIn0Arr
#define _CropPack4OutArr _TexOut0Arr
#define _SlicePack4InArr _TexIn0Arr
#define _SlicePack4OutArr _TexOut0Arr
#define _SlicePack4CDHWInArr _TexIn0Arr
#define _SlicePack4CDHWOutArr _TexOut0Arr
#define _PermutePack4InArr _TexIn0Arr
#define _PermutePack4OutArr _TexOut0Arr
#define _PermutePack4CDHWInArr _TexIn0Arr
#define _PermutePack4CDHWOutArr _TexOut0Arr
#define _WindowPartitionPack4InArr _TexIn0Arr
#define _WindowPartitionPack4OutArr _TexOut0Arr
#define _WindowUnpartitionPack4InArr _TexIn0Arr
#define _WindowUnpartitionPack4OutArr _TexOut0Arr
#define _ReshapePack4ToScalar2DInArr _TexIn0Arr
#define _ReshapePack4ToScalar2DOutArr _TexOut0Arr
#define _ReshapePack4ToPack4InArr _TexIn0Arr
#define _ReshapePack4ToPack4OutArr _TexOut0Arr
#define _ReshapeScalar2DInArr _TexIn0Arr
#define _ReshapeScalar2DOutArr _TexOut0Arr
#define _AttentionReshapeInArr _TexIn0Arr
#define _AttentionReshapeOutArr _TexOut0Arr
#define _AttentionContextFlattenInArr _TexIn0Arr
#define _AttentionContextFlattenOutArr _TexOut0Arr
#define _ActInArr _TexIn0Arr
#define _ActOutArr _TexOut0Arr
#define _GemmTexAInArr _TexIn0Arr
#define _GemmTexOutArr _TexOut0Arr
#define _MatPack4AInArr _TexIn0Arr
#define _MatPack4BInArr _TexIn1Arr
#define _MatPack4OutArr _TexOut0Arr
#define _VistaTailInArr _TexIn0Arr
#define _VistaTailPromptTex _TexIn1Arr
#define _VistaTailOutArr _TexOut0Arr
#define _LnTexInArr _TexIn0Arr
#define _LnTexOutArr _TexOut0Arr
#define _SoftmaxPack4CDHWInArr _TexIn0Arr
#define _SoftmaxPack4CDHWOutArr _TexOut0Arr
#define _GnTexInArr _TexIn0Arr
#define _GnTexOutArr _TexOut0Arr
#define _GnStatsTexIn _TexIn1Arr
#define _GnStatsTexOut _TexOut1Arr
#define _MaxPoolInArr _TexIn0Arr
#define _MaxPoolPooledArr _TexIn1Arr
#define _MaxPoolOutArr _TexOut0Arr
#define _MaxPoolIndicesArr _TexOut1Arr
#define _MaxUnpoolInArr _TexIn0Arr
#define _MaxUnpoolIndicesArr _TexIn1Arr
#define _MaxUnpoolOutArr _TexOut0Arr
#define _ReorgInArr _TexIn0Arr
#define _ReorgOutArr _TexOut0Arr
#define _PointwiseInArr _TexIn0Arr
#define _PointwiseOutArr _TexOut0Arr
#define _PixelShufflePack4InArr _TexIn0Arr
#define _PixelShufflePack4OutArr _TexOut0Arr
